export const FETCH_NEWS_START = "FETCH_NEWS_START";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAIL = "FETCH_NEWS_FAIL";

export const SEARCH_NEWS_START = "SEARCH_NEWS_START";
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS";
export const SEARCH_NEWS_FAIL = "SEARCH_NEWS_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const REMOVE_ERROR = "REMOVE_ERROR";
